import type { NextApiRequest, NextApiResponse } from 'next';
import { getDailyInsights } from '../../lib/getDailyInsights';
import type { DailyInsights, APIConfig, RedisConfig } from '../../lib/types';

// Mock data for when API keys aren't configured - 35+ NSE stocks
const MOCK_INSIGHTS: DailyInsights = {
    date: new Date().toISOString().split('T')[0],
    marketSummary: {
        totalVolume: 125000000,
        advancers: 38,
        decliners: 24,
        unchanged: 18,
    },
    picks: [
        // TOP TIER BLUE CHIPS
        {
            ticker: 'SCOM',
            name: 'Safaricom PLC',
            currentPrice: 25.50,
            entryPoint: 25.00,
            stopLoss: 23.75,
            targetPrice: 27.50,
            reasoning: 'Market leader. 5.8% dividend yield + M-Pesa dominance. Strong momentum.',
            momentumScore: 75,
            dividendScore: 85,
            totalScore: 79,
            volumeSpike: 15.2,
        },
        {
            ticker: 'EQTY',
            name: 'Equity Group Holdings',
            currentPrice: 55.25,
            entryPoint: 54.50,
            stopLoss: 51.00,
            targetPrice: 60.00,
            reasoning: 'Digital banking leader. 20-day MA breakout with fintech growth.',
            momentumScore: 82,
            dividendScore: 58,
            totalScore: 73,
            volumeSpike: 22.1,
        },
        {
            ticker: 'KCB',
            name: 'KCB Group',
            currentPrice: 38.75,
            entryPoint: 38.00,
            stopLoss: 35.50,
            targetPrice: 42.50,
            reasoning: 'Regional expansion. 18% volume surge with strong Q4 earnings ahead.',
            momentumScore: 78,
            dividendScore: 65,
            totalScore: 73,
            volumeSpike: 18.3,
        },
        {
            ticker: 'EABL',
            name: 'East African Breweries',
            currentPrice: 185.00,
            entryPoint: 183.60,
            stopLoss: 171.00,
            targetPrice: 203.50,
            reasoning: 'Consumer staples resilience. 6.2% dividend yield, defensive play.',
            momentumScore: 68,
            dividendScore: 78,
            totalScore: 72,
            volumeSpike: 12.8,
        },

        // BANKING SECTOR
        {
            ticker: 'IMHC',
            name: 'I&M Holdings',
            currentPrice: 42.50,
            entryPoint: 41.80,
            stopLoss: 38.95,
            targetPrice: 46.75,
            reasoning: '7.1% dividend yield. Acquisition synergies improving ROE.',
            momentumScore: 65,
            dividendScore: 82,
            totalScore: 72,
            volumeSpike: 11.5,
        },
        {
            ticker: 'COOP',
            name: 'Co-operative Bank',
            currentPrice: 16.40,
            entryPoint: 16.00,
            stopLoss: 15.00,
            targetPrice: 18.00,
            reasoning: 'Value play. 6.8% yield with strong loan book growth.',
            momentumScore: 62,
            dividendScore: 76,
            totalScore: 68,
            volumeSpike: 9.8,
        },
        {
            ticker: 'ABSA',
            name: 'Absa Bank Kenya',
            currentPrice: 14.85,
            entryPoint: 14.50,
            stopLoss: 13.50,
            targetPrice: 16.20,
            reasoning: 'Post-rebranding gains. 7.2% yield attracts income investors.',
            momentumScore: 58,
            dividendScore: 80,
            totalScore: 67,
            volumeSpike: 8.5,
        },
        {
            ticker: 'SCBK',
            name: 'Standard Chartered Bank',
            currentPrice: 168.00,
            entryPoint: 165.00,
            stopLoss: 155.00,
            targetPrice: 182.00,
            reasoning: 'Premium banking franchise. Corporate lending recovery.',
            momentumScore: 70,
            dividendScore: 68,
            totalScore: 69,
            volumeSpike: 12.3,
        },
        {
            ticker: 'DTB',
            name: 'Diamond Trust Bank',
            currentPrice: 82.50,
            entryPoint: 80.00,
            stopLoss: 74.00,
            targetPrice: 92.00,
            reasoning: 'Regional expansion play. 5.5% dividend with SME focus.',
            momentumScore: 66,
            dividendScore: 70,
            totalScore: 68,
            volumeSpike: 10.7,
        },
        {
            ticker: 'NBK',
            name: 'National Bank of Kenya',
            currentPrice: 6.85,
            entryPoint: 6.50,
            stopLoss: 5.80,
            targetPrice: 7.80,
            reasoning: 'Turnaround story. High-risk with 28% volume spike.',
            momentumScore: 75,
            dividendScore: 42,
            totalScore: 62,
            volumeSpike: 28.4,
        },

        // MANUFACTURING & CONSTRUCTION
        {
            ticker: 'BAMB',
            name: 'Bamburi Cement',
            currentPrice: 32.80,
            entryPoint: 32.00,
            stopLoss: 29.50,
            targetPrice: 36.50,
            reasoning: 'Infrastructure boom. 5.5% yield with volume spike.',
            momentumScore: 70,
            dividendScore: 72,
            totalScore: 71,
            volumeSpike: 14.2,
        },
        {
            ticker: 'CABL',
            name: 'Carbacid Investments',
            currentPrice: 18.25,
            entryPoint: 17.80,
            stopLoss: 16.20,
            targetPrice: 20.50,
            reasoning: 'CO2 monopoly. Beverage sector growth with 4.8% yield.',
            momentumScore: 64,
            dividendScore: 67,
            totalScore: 65,
            volumeSpike: 9.3,
        },
        {
            ticker: 'ARM',
            name: 'ARM Cement',
            currentPrice: 3.20,
            entryPoint: 3.00,
            stopLoss: 2.50,
            targetPrice: 3.85,
            reasoning: 'Deep value. Restructuring play with high risk.',
            momentumScore: 58,
            dividendScore: 25,
            totalScore: 45,
            volumeSpike: 32.1,
        },
        {
            ticker: 'BATK',
            name: 'BAT Kenya',
            currentPrice: 420.00,
            entryPoint: 415.00,
            stopLoss: 390.00,
            targetPrice: 455.00,
            reasoning: 'Defensive dividend aristocrat. 8.5% yield, stable cash flow.',
            momentumScore: 52,
            dividendScore: 92,
            totalScore: 68,
            volumeSpike: 5.7,
        },
        {
            ticker: 'UNGA',
            name: 'Unga Group',
            currentPrice: 42.00,
            entryPoint: 41.00,
            stopLoss: 38.00,
            targetPrice: 46.50,
            reasoning: 'Staple food. Inflation hedge with margin improvement.',
            momentumScore: 67,
            dividendScore: 61,
            totalScore: 64,
            volumeSpike: 10.5,
        },
        {
            ticker: 'BOC',
            name: 'BOC Kenya',
            currentPrice: 38.50,
            entryPoint: 37.50,
            stopLoss: 34.50,
            targetPrice: 42.50,
            reasoning: 'Industrial gases leader. Manufacturing recovery play.',
            momentumScore: 69,
            dividendScore: 64,
            totalScore: 67,
            volumeSpike: 11.2,
        },

        // ENERGY & UTILITIES
        {
            ticker: 'KPLC',
            name: 'Kenya Power & Lighting',
            currentPrice: 2.45,
            entryPoint: 2.35,
            stopLoss: 2.10,
            targetPrice: 2.85,
            reasoning: 'Restructuring progress. High-risk turnaround with 25% spike.',
            momentumScore: 72,
            dividendScore: 35,
            totalScore: 58,
            volumeSpike: 25.6,
        },
        {
            ticker: 'KENGEN',
            name: 'KenGen',
            currentPrice: 3.85,
            entryPoint: 3.75,
            stopLoss: 3.40,
            targetPrice: 4.35,
            reasoning: 'Renewable energy. 5.0% yield with govt support.',
            momentumScore: 64,
            dividendScore: 68,
            totalScore: 66,
            volumeSpike: 10.2,
        },
        {
            ticker: 'KEGN',
            name: 'Kenya Electricity Generating',
            currentPrice: 4.20,
            entryPoint: 4.05,
            stopLoss: 3.70,
            targetPrice: 4.75,
            reasoning: 'Geothermal expansion. Green energy catalyst.',
            momentumScore: 68,
            dividendScore: 66,
            totalScore: 67,
            volumeSpike: 13.8,
        },
        {
            ticker: 'TOTL',
            name: 'Total Energies Kenya',
            currentPrice: 22.80,
            entryPoint: 22.20,
            stopLoss: 20.50,
            targetPrice: 25.50,
            reasoning: 'Oil retail leader. 6.5% dividend, stable cash generation.',
            momentumScore: 61,
            dividendScore: 73,
            totalScore: 66,
            volumeSpike: 8.9,
        },

        // AGRICULTURE
        {
            ticker: 'SASINI',
            name: 'Sasini PLC',
            currentPrice: 12.50,
            entryPoint: 12.00,
            stopLoss: 10.80,
            targetPrice: 14.00,
            reasoning: 'Tea prices rebounding. Agriculture recovery, 6.5% yield.',
            momentumScore: 66,
            dividendScore: 70,
            totalScore: 68,
            volumeSpike: 11.8,
        },
        {
            ticker: 'KCSE',
            name: 'Kakuzi PLC',
            currentPrice: 385.00,
            entryPoint: 380.00,
            stopLoss: 355.00,
            targetPrice: 420.00,
            reasoning: 'Avocado export boom. Niche agribusiness, 4.8% yield.',
            momentumScore: 68,
            dividendScore: 64,
            totalScore: 66,
            volumeSpike: 13.4,
        },
        {
            ticker: 'WTK',
            name: 'Williamson Tea Kenya',
            currentPrice: 165.00,
            entryPoint: 160.00,
            stopLoss: 148.00,
            targetPrice: 182.00,
            reasoning: 'Premium tea producer. Export market strength.',
            momentumScore: 63,
            dividendScore: 68,
            totalScore: 65,
            volumeSpike: 9.7,
        },
        {
            ticker: 'KAPC',
            name: 'Kapchorua Tea',
            currentPrice: 48.50,
            entryPoint: 47.00,
            stopLoss: 43.50,
            targetPrice: 53.50,
            reasoning: 'Small-cap tea play. High volatility with 5.2% yield.',
            momentumScore: 70,
            dividendScore: 62,
            totalScore: 67,
            volumeSpike: 15.3,
        },

        // INSURANCE
        {
            ticker: 'BRIT',
            name: 'Britam Holdings',
            currentPrice: 7.20,
            entryPoint: 7.00,
            stopLoss: 6.30,
            targetPrice: 8.10,
            reasoning: 'Sector consolidation. Improving underwriting ratios.',
            momentumScore: 60,
            dividendScore: 62,
            totalScore: 61,
            volumeSpike: 7.9,
        },
        {
            ticker: 'JBIC',
            name: 'Jubilee Holdings',
            currentPrice: 280.00,
            entryPoint: 275.00,
            stopLoss: 255.00,
            targetPrice: 310.00,
            reasoning: 'Regional insurance leader. 5.8% dividend yield.',
            momentumScore: 65,
            dividendScore: 70,
            totalScore: 67,
            volumeSpike: 10.4,
        },
        {
            ticker: 'CIC',
            name: 'CIC Insurance Group',
            currentPrice: 2.95,
            entryPoint: 2.85,
            stopLoss: 2.55,
            targetPrice: 3.35,
            reasoning: 'Value insurance play. Improving loss ratios.',
            momentumScore: 62,
            dividendScore: 58,
            totalScore: 60,
            volumeSpike: 12.7,
        },

        // REAL ESTATE & HOSPITALITY
        {
            ticker: 'HFCK',
            name: 'HF Group',
            currentPrice: 4.15,
            entryPoint: 4.00,
            stopLoss: 3.60,
            targetPrice: 4.70,
            reasoning: 'Mortgage finance recovery. High-risk turnaround.',
            momentumScore: 68,
            dividendScore: 45,
            totalScore: 59,
            volumeSpike: 18.9,
        },
        {
            ticker: 'SENO',
            name: 'Stanlib Fahari I-REIT',
            currentPrice: 6.80,
            entryPoint: 6.60,
            stopLoss: 6.10,
            targetPrice: 7.50,
            reasoning: 'REIT play. Real estate exposure with 7.0% yield.',
            momentumScore: 55,
            dividendScore: 76,
            totalScore: 64,
            volumeSpike: 6.8,
        },

        // MEDIA & TELECOM
        {
            ticker: 'TPSE',
            name: 'Standard Group',
            currentPrice: 18.50,
            entryPoint: 18.00,
            stopLoss: 16.20,
            targetPrice: 21.00,
            reasoning: 'Media recovery. Digital transformation play.',
            momentumScore: 63,
            dividendScore: 55,
            totalScore: 60,
            volumeSpike: 16.7,
        },
        {
            ticker: 'SCAN',
            name: 'Scangroup',
            currentPrice: 7.85,
            entryPoint: 7.50,
            stopLoss: 6.80,
            targetPrice: 8.90,
            reasoning: 'Advertising recovery. Post-pandemic rebound.',
            momentumScore: 67,
            dividendScore: 52,
            totalScore: 61,
            volumeSpike: 14.5,
        },
        {
            ticker: 'ATHI',
            name: 'Athi River Mining',
            currentPrice: 4.75,
            entryPoint: 4.55,
            stopLoss: 4.10,
            targetPrice: 5.35,
            reasoning: 'Cement diversification. Infrastructure tailwind.',
            momentumScore: 71,
            dividendScore: 56,
            totalScore: 65,
            volumeSpike: 17.2,
        },

        // INVESTMENT & SERVICES
        {
            ticker: 'ICDC',
            name: 'ICDC',
            currentPrice: 3.45,
            entryPoint: 3.30,
            stopLoss: 3.00,
            targetPrice: 3.90,
            reasoning: 'Development finance. Govt-backed with stable income.',
            momentumScore: 58,
            dividendScore: 65,
            totalScore: 61,
            volumeSpike: 8.3,
        },
        {
            ticker: 'KURV',
            name: 'Kurwitu Ventures',
            currentPrice: 9.20,
            entryPoint: 8.90,
            stopLoss: 8.10,
            targetPrice: 10.50,
            reasoning: 'Investment firm. Portfolio diversification play.',
            momentumScore: 64,
            dividendScore: 60,
            totalScore: 62,
            volumeSpike: 11.6,
        },
        {
            ticker: 'LIMT',
            name: 'Limuru Tea',
            currentPrice: 295.00,
            entryPoint: 290.00,
            stopLoss: 270.00,
            targetPrice: 325.00,
            reasoning: 'Premium tea estate. Export quality with 4.2% yield.',
            momentumScore: 66,
            dividendScore: 63,
            totalScore: 65,
            volumeSpike: 7.4,
        },
    ],
    cacheHit: false,
    dataFreshnessMinutes: 0,
};

export default async function handler(
    req: NextApiRequest,
    res: NextApiResponse<DailyInsights | { error: string }>
) {
    // Only allow GET requests
    if (req.method !== 'GET') {
        return res.status(405).json({ error: 'Method not allowed' });
    }

    try {
        // Check if API keys are configured
        const hasApiKeys = process.env.NEXT_PUBLIC_NSE_API_URL && process.env.REDIS_URL;

        if (!hasApiKeys) {
            // Return mock data if no API keys configured
            console.log('📊 Using mock data (API keys not configured)');
            return res.status(200).json(MOCK_INSIGHTS);
        }

        // API Configuration from environment variables
        const apiConfig: APIConfig = {
            baseUrl: process.env.NEXT_PUBLIC_NSE_API_URL || '',
            apiKey: process.env.NEXT_PUBLIC_NSE_API_KEY || '',
            timeout: 10000,
            retryAttempts: 3,
        };

        // Redis Configuration
        const redisConfig: RedisConfig = {
            url: process.env.REDIS_URL || '',
            password: process.env.REDIS_PASSWORD,
            ttl: 900, // 15 minutes
        };

        // Fetch daily insights
        const insights = await getDailyInsights(apiConfig, redisConfig);

        // Return data
        res.status(200).json(insights);
    } catch (error) {
        console.error('API Error:', error);

        // Fallback to mock data on error
        console.log('⚠️ API error, returning mock data as fallback');
        res.status(200).json(MOCK_INSIGHTS);
    }
}
